/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class mycal extends javax.swing.JFrame {
double num1=0,num2=0;
String operator=null;
    /**
     * Creates new form mycal
     */
    public mycal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        b7 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        bclear = new javax.swing.JButton();
        bback = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        bsub = new javax.swing.JButton();
        bplus = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bequal = new javax.swing.JButton();
        bdot = new javax.swing.JButton();
        bsqrt = new javax.swing.JButton();
        bpower = new javax.swing.JButton();
        bkebnar = new javax.swing.JButton();
        bceil = new javax.swing.JButton();
        bfloor = new javax.swing.JButton();
        log = new javax.swing.JButton();
        log10 = new javax.swing.JButton();
        max = new javax.swing.JButton();
        min = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        bround = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        sinh = new javax.swing.JButton();
        cosh = new javax.swing.JButton();
        tanh = new javax.swing.JButton();
        asin = new javax.swing.JButton();
        acos = new javax.swing.JButton();
        atan = new javax.swing.JButton();
        todegree = new javax.swing.JButton();
        toradian = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        off = new javax.swing.JButton();
        on = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jButton3.setText("7");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\.vscode\\extensions\\techer.open-in-browser-2.0.0\\images\\kebnar\\cloud2.jpg")); // NOI18N
        jLabel9.setText("jLabel4");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\.vscode\\extensions\\techer.open-in-browser-2.0.0\\images\\kebnar\\cloud2.jpg")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\.vscode\\extensions\\techer.open-in-browser-2.0.0\\images\\kebnar\\cloud2.jpg")); // NOI18N
        jLabel6.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\.vscode\\extensions\\techer.open-in-browser-2.0.0\\images\\kebnar\\cloud2.jpg")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\.vscode\\extensions\\techer.open-in-browser-2.0.0\\images\\kebnar\\cloud2.jpg")); // NOI18N
        jLabel7.setText("jLabel4");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\.vscode\\extensions\\techer.open-in-browser-2.0.0\\images\\kebnar\\cloud2.jpg")); // NOI18N
        jLabel8.setText("jLabel4");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\.vscode\\extensions\\techer.open-in-browser-2.0.0\\images\\kebnar\\cloud2.jpg")); // NOI18N
        jLabel10.setText("jLabel4");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\.vscode\\extensions\\techer.open-in-browser-2.0.0\\images\\kebnar\\jems.jpg")); // NOI18N
        jLabel11.setText("jLabel11");

        jPanel3.setBackground(new java.awt.Color(204, 255, 153));
        jPanel3.setForeground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Kebnar Calculator");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 240, 40));

        t1.setBackground(new java.awt.Color(0, 102, 102));
        t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(0, 0, 51));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 570, 40));

        b7.setBackground(new java.awt.Color(51, 255, 51));
        b7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 54, 39));

        b9.setBackground(new java.awt.Color(51, 51, 255));
        b9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 54, 39));

        b8.setBackground(new java.awt.Color(0, 255, 255));
        b8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 54, 39));

        b4.setBackground(new java.awt.Color(255, 0, 153));
        b4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 54, 39));

        b6.setBackground(new java.awt.Color(0, 204, 204));
        b6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 54, 39));

        b5.setBackground(new java.awt.Color(204, 204, 255));
        b5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 54, 39));

        b1.setBackground(new java.awt.Color(0, 255, 255));
        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 54, 39));

        b3.setBackground(new java.awt.Color(102, 255, 102));
        b3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 54, 39));

        b2.setBackground(new java.awt.Color(102, 0, 102));
        b2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 54, 39));

        bclear.setBackground(new java.awt.Color(255, 51, 51));
        bclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bclear.setText("clear");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        getContentPane().add(bclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 140, 60));

        bback.setBackground(new java.awt.Color(51, 255, 255));
        bback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bback.setText("back");
        bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackActionPerformed(evt);
            }
        });
        getContentPane().add(bback, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 120, 60));

        bmul.setBackground(new java.awt.Color(153, 153, 0));
        bmul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bmul.setText("x");
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });
        getContentPane().add(bmul, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 49, 39));

        bdiv.setBackground(new java.awt.Color(204, 0, 204));
        bdiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bdiv.setText("/");
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });
        getContentPane().add(bdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 49, 39));

        bsub.setBackground(new java.awt.Color(51, 51, 255));
        bsub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bsub.setText("-");
        bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubActionPerformed(evt);
            }
        });
        getContentPane().add(bsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 49, 39));

        bplus.setBackground(new java.awt.Color(255, 204, 204));
        bplus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bplus.setText("+");
        bplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bplusActionPerformed(evt);
            }
        });
        getContentPane().add(bplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 49, 39));

        b0.setBackground(new java.awt.Color(51, 255, 255));
        b0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        getContentPane().add(b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 54, 39));

        bequal.setBackground(new java.awt.Color(255, 255, 0));
        bequal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bequal.setText("=");
        bequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bequalActionPerformed(evt);
            }
        });
        getContentPane().add(bequal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 54, 39));

        bdot.setBackground(new java.awt.Color(102, 255, 102));
        bdot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bdot.setText(".");
        bdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdotActionPerformed(evt);
            }
        });
        getContentPane().add(bdot, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 54, 39));

        bsqrt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bsqrt.setText("sqrt");
        bsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsqrtActionPerformed(evt);
            }
        });
        getContentPane().add(bsqrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 70, 90));

        bpower.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bpower.setText("pow");
        bpower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpowerActionPerformed(evt);
            }
        });
        getContentPane().add(bpower, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, 50));

        bkebnar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bkebnar.setText("kebnar");
        bkebnar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkebnarActionPerformed(evt);
            }
        });
        getContentPane().add(bkebnar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 160, 40));

        bceil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bceil.setText("ceil");
        bceil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bceilActionPerformed(evt);
            }
        });
        getContentPane().add(bceil, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 70, 40));

        bfloor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bfloor.setText("floor");
        bfloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfloorActionPerformed(evt);
            }
        });
        getContentPane().add(bfloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 363, 90, 50));

        log.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        log.setText("log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        getContentPane().add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 80, 50));

        log10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        log10.setText("log10");
        log10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log10ActionPerformed(evt);
            }
        });
        getContentPane().add(log10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 213, 90, 40));

        max.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        max.setText("max");
        max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxActionPerformed(evt);
            }
        });
        getContentPane().add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 80, 40));

        min.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        min.setText("min");
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 80, 40));

        sin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        getContentPane().add(sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 80, 40));

        cos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        getContentPane().add(cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 80, 40));

        bround.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bround.setText("round");
        bround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broundActionPerformed(evt);
            }
        });
        getContentPane().add(bround, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 90, 40));

        tan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        getContentPane().add(tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 80, 40));

        sinh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sinh.setText("sinh");
        sinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinhActionPerformed(evt);
            }
        });
        getContentPane().add(sinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 80, 40));

        cosh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cosh.setText("cosh");
        cosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coshActionPerformed(evt);
            }
        });
        getContentPane().add(cosh, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 80, 30));

        tanh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tanh.setText("tanh");
        tanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanhActionPerformed(evt);
            }
        });
        getContentPane().add(tanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 80, 30));

        asin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        asin.setText("asin");
        asin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asinActionPerformed(evt);
            }
        });
        getContentPane().add(asin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 80, 30));

        acos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        acos.setText("acos");
        acos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acosActionPerformed(evt);
            }
        });
        getContentPane().add(acos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 80, 30));

        atan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        atan.setText("atan");
        atan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atanActionPerformed(evt);
            }
        });
        getContentPane().add(atan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 80, 50));

        todegree.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        todegree.setText("toDegree");
        todegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todegreeActionPerformed(evt);
            }
        });
        getContentPane().add(todegree, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, 40));

        toradian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        toradian.setText("toRadian");
        toradian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toradianActionPerformed(evt);
            }
        });
        getContentPane().add(toradian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 130, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 570, 370));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\.vscode\\extensions\\techer.open-in-browser-2.0.0\\images\\kebnar\\jems.jpg")); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -120, 480, 690));

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 255)));

        off.setBackground(new java.awt.Color(255, 51, 51));
        off.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        off.setText("OFF");
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        on.setBackground(new java.awt.Color(51, 255, 51));
        on.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        on.setText("ON");
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(off, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(on, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 419, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(off, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(on, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 570, 40));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 90, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 90, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        String on="1";
        String one=t1.getText()+on;
        t1.setText(one);
         
    }//GEN-LAST:event_b1ActionPerformed

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        // TODO add your handling code here:
        t1.setText("");
    }//GEN-LAST:event_bclearActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        String zer="0";
        String zero=t1.getText()+zer;
        t1.setText(zero);
    }//GEN-LAST:event_b0ActionPerformed

    private void bdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdotActionPerformed
        // TODO add your handling code here:
        String dot=".";
        String dotter =t1.getText()+dot;
        t1.setText(dotter);
    }//GEN-LAST:event_bdotActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        String sev="7";
        String seven=t1.getText()+sev;
        t1.setText(seven);
        
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        String eigh="8";
        String eight=t1.getText()+eigh;
        t1.setText(eight);
        
        
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
         String nin="9";
        String nine=t1.getText()+nin;
        t1.setText(nine);
    }//GEN-LAST:event_b9ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
         String fort="4";
        String four=t1.getText()+fort;
        t1.setText(four);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
         String fiv="5";
        String five=t1.getText()+fiv;
        t1.setText(five);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
         String sex="6";
        String six=t1.getText()+sex;
        t1.setText(six);
    }//GEN-LAST:event_b6ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         String tow="2";
        String two=t1.getText()+tow;
        t1.setText(two);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        String tree="3";
        String three=t1.getText()+tree;
        t1.setText(three);
    }//GEN-LAST:event_b3ActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
        // TODO add your handling code here:
        String div=t1.getText();//first take an input
        num1=Double.parseDouble(div);//parse it to double and store on num1
         t1.setText("");//then remove it from screen
         operator="/";//identify the operator
    }//GEN-LAST:event_bdivActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
        // TODO add your handling code here:
       String mul=t1.getText();
        num1=Double.parseDouble(mul);
         t1.setText("");
         operator="*";
    }//GEN-LAST:event_bmulActionPerformed

    private void bsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubActionPerformed
        // TODO add your handling code here:
      String sub=t1.getText();
        num1=Double.parseDouble(sub);
         t1.setText("");
         operator="-";
    }//GEN-LAST:event_bsubActionPerformed

    private void bplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bplusActionPerformed
        // TODO add your handling code here:
        String plus=t1.getText();
        num1=Double.parseDouble(plus);
         t1.setText("");
         operator="+";
    }//GEN-LAST:event_bplusActionPerformed

    private void bequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bequalActionPerformed
        // TODO add your handling code here:
        num2=Double.parseDouble(t1.getText());
        double ans=0;
         if(operator=="+"){
         ans=num1+num2;
         t1.setText(""+"("+num1+"+"+num2+")"+"="+ans);         
         }
         if(operator=="-"){
             ans=num1-num2;
             t1.setText(""+"("+num1+"-"+num2+")"+"="+ans);         
         }
         if(operator=="*"){
             ans=num1*num2;
             t1.setText(""+"("+num1+"*"+num2+")"+"="+ans);         
         }
         if(operator=="max"){
         ans=Math.max(num1, num2);
         t1.setText(""+"MAX"+"("+num1+","+num2+")"+"="+ans);         
              }
         if(operator=="min"){
         ans=Math.min(num1, num2);
                t1.setText(""+"MIN"+"("+num1+","+num2+")"+"="+ans);         
         }
         if(operator=="/"){
             ans=num1/num2;
              t1.setText(""+"("+num1+"/"+num2+")"+"="+ans);
         }if(operator=="power"){
             String s=t1.getText();
             num2=Double.parseDouble(s);
             ans=Math.pow(num1, num2);
              t1.setText("("+num1+"^"+num2+")"+"="+ans);
         }
           
            operator=null;
         
        
    }//GEN-LAST:event_bequalActionPerformed

    private void bbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackActionPerformed
        // TODO add your handling code here:
        String str=t1.getText();
        t1.setText(str.substring(0,str.length()-1));
        
    }//GEN-LAST:event_bbackActionPerformed

    private void bkebnarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkebnarActionPerformed
        // TODO add your handling code here:
        String kebo="kebnar seminaran jedhama";
        String kebnar=t1.getText()+kebo;
        t1.setText(kebnar);
    }//GEN-LAST:event_bkebnarActionPerformed

    private void bsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsqrtActionPerformed
        // TODO add your handling code here:
       
        String sqr=t1.getText();
        num1=Math.sqrt(Double.parseDouble(sqr));
         t1.setText("sqrt"+"("+t1.getText()+")"+"="+num1);//finished at this without clicking equal sign
         
        
    }//GEN-LAST:event_bsqrtActionPerformed

    private void bpowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpowerActionPerformed
        // TODO add your handling code here:
         String sq=t1.getText();
         num1=Double.parseDouble(sq);
         t1.setText("");
         operator="power";
         
    }//GEN-LAST:event_bpowerActionPerformed

    private void bceilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bceilActionPerformed
        // TODO add your handling code here:
        String ce=t1.getText();
        num1=Math.ceil(Double.parseDouble(ce));
        t1.setText("ceil"+"("+t1.getText()+")"+"="+num1);
        
    }//GEN-LAST:event_bceilActionPerformed

    private void bfloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfloorActionPerformed
        // TODO add your handling code here:
        String flo=t1.getText();
        num1=Math.floor(Double.parseDouble(flo));
        t1.setText("floor"+"("+t1.getText()+")"+"="+num1);
        
    }//GEN-LAST:event_bfloorActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // TODO add your handling code here:
        String sin=t1.getText();
        num1=Math.sin(Double.parseDouble(sin));
        t1.setText("sin"+"("+t1.getText()+")"+"="+num1);
    }//GEN-LAST:event_sinActionPerformed

    private void acosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acosActionPerformed
        // TODO add your handling code here:
        String acos=t1.getText();
        num1=Math.acos(Double.parseDouble(acos));
        t1.setText("acos"+"("+t1.getText()+")"+"="+num1);
    }//GEN-LAST:event_acosActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // TODO add your handling code here:
        String cos=t1.getText();
        num1=Math.cos(Double.parseDouble(cos));
        t1.setText("cos"+"("+t1.getText()+")"+"="+num1);
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // TODO add your handling code here:
        String tan=t1.getText();
        num1=Math.tan(Double.parseDouble(tan));
        t1.setText("tan"+"("+t1.getText()+")"+"="+num1);
    }//GEN-LAST:event_tanActionPerformed

    private void sinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinhActionPerformed
        // TODO add your handling code here:
        String sinh=t1.getText();
        num1=Math.sinh(Double.parseDouble(sinh));
        t1.setText("sinh"+"("+t1.getText()+")"+"="+num1);
    }//GEN-LAST:event_sinhActionPerformed

    private void coshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coshActionPerformed
        // TODO add your handling code here:
        String cosh=t1.getText();
        num1=Math.cosh(Double.parseDouble(cosh));
        t1.setText("cosh"+"("+t1.getText()+")"+"="+num1);
    }//GEN-LAST:event_coshActionPerformed

    private void tanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanhActionPerformed
        // TODO add your handling code here:
        String tanh=t1.getText();
        num1=Math.tanh(Double.parseDouble(tanh));
        t1.setText("tanh"+"("+t1.getText()+")"+"="+num1);
    }//GEN-LAST:event_tanhActionPerformed

    private void asinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asinActionPerformed
        // TODO add your handling code here:
        String asin=t1.getText();
        num1=Math.asin(Double.parseDouble(asin));
        t1.setText("asin"+"("+t1.getText()+")"+"="+num1);
    }//GEN-LAST:event_asinActionPerformed

    private void atanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atanActionPerformed
        // TODO add your handling code here:
        String atan=t1.getText();
        num1=Math.atan(Double.parseDouble(atan));
        t1.setText("atan"+"("+t1.getText()+")"+"="+num1);
        
    }//GEN-LAST:event_atanActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
        String log=t1.getText();
        num1=Math.log(Double.parseDouble(log));
        t1.setText("log"+"("+t1.getText()+")"+"="+num1); 
    }//GEN-LAST:event_logActionPerformed

    private void log10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log10ActionPerformed
        // TODO add your handling code here:
        String log10=t1.getText();
        num1=Math.log10(Double.parseDouble(log10));
        t1.setText("log10"+"("+t1.getText()+")"+"="+num1);
        
        
    }//GEN-LAST:event_log10ActionPerformed

    private void todegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todegreeActionPerformed
        // TODO add your handling code here:
        String todeg=t1.getText();
        num1=Math.toDegrees(Double.parseDouble(todeg));
        t1.setText(""+"("+t1.getText()+")"+"="+num1+"deg");
        
    }//GEN-LAST:event_todegreeActionPerformed

    private void toradianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toradianActionPerformed
        // TODO add your handling code here:
        String torad=t1.getText();
        num1=Math.toRadians(Double.parseDouble(torad));
        t1.setText(""+"("+t1.getText()+")"+"="+num1+"rad");
    }//GEN-LAST:event_toradianActionPerformed

    private void broundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broundActionPerformed
        // TODO add your handling code here:
        String numb=t1.getText();
        num1=Math.round(Double.parseDouble(numb));
        t1.setText("roundoff"+"("+t1.getText()+")"+"="+num1);
    }//GEN-LAST:event_broundActionPerformed

    private void maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxActionPerformed
        // TODO add your handling code here:
       String max=t1.getText();
       num1=Double.parseDouble(max);
       t1.setText("");
       operator="max";
    }//GEN-LAST:event_maxActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        // TODO add your handling code here:
        String min=t1.getText();
       num1=Double.parseDouble(min);
       t1.setText("");
       operator="min";
    }//GEN-LAST:event_minActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        // TODO add your handling code here:
         t1.setEnabled(true);
         b0.setEnabled(true);
         b1.setEnabled(true);
         b2.setEnabled(true);
         b3.setEnabled(true);
         b4.setEnabled(true);
         b5.setEnabled(true);
         b6.setEnabled(true);
         b7.setEnabled(true);
         b8.setEnabled(true);
         b9.setEnabled(true);
         bdiv.setEnabled(true);
         bmul.setEnabled(true);
         bsub.setEnabled(true);
         bplus.setEnabled(true);
         bequal.setEnabled(true);
         bdot.setEnabled(true);
         bfloor.setEnabled(true);
         bround.setEnabled(true);
         bceil.setEnabled(true);
         bsqrt.setEnabled(true);
         bback.setEnabled(true);
          bclear.setEnabled(true);
         bpower.setEnabled(true);
         todegree.setEnabled(true);
         max.setEnabled(true);
         min.setEnabled(true);
         toradian.setEnabled(true);
         sin.setEnabled(true);
         cos.setEnabled(true);
         tan.setEnabled(true);
         cosh.setEnabled(true);
         sinh.setEnabled(true);
         tanh.setEnabled(true);
         atan.setEnabled(true);
         asin.setEnabled(true);
         acos.setEnabled(true);
         log.setEnabled(true);
         log10.setEnabled(true);
          bkebnar.setEnabled(true);
        
         
    }//GEN-LAST:event_onActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        // TODO add your handling code here:
        t1.setEnabled(false);
        t1.setEnabled(false);
         b0.setEnabled(false);
         b1.setEnabled(false);
         b2.setEnabled(false);
         b3.setEnabled(false);
         b4.setEnabled(false);
         b5.setEnabled(false);
         b6.setEnabled(false);
         b7.setEnabled(false);
         b8.setEnabled(false);
         b9.setEnabled(false);
         bdiv.setEnabled(false);
         bmul.setEnabled(false);
         bsub.setEnabled(false);
         bplus.setEnabled(false);
         bequal.setEnabled(false);
         bdot.setEnabled(false);
         bfloor.setEnabled(false);
         bround.setEnabled(false);
         bceil.setEnabled(false);
         bsqrt.setEnabled(false);
         bback.setEnabled(false);
          bclear.setEnabled(false);
         bpower.setEnabled(false);
         todegree.setEnabled(false);
         max.setEnabled(false);
         min.setEnabled(false);
         toradian.setEnabled(false);
         sin.setEnabled(false);
         cos.setEnabled(false);
         tan.setEnabled(false);
         cosh.setEnabled(false);
         sinh.setEnabled(false);
         tanh.setEnabled(false);
         atan.setEnabled(false);
         asin.setEnabled(false);
         acos.setEnabled(false);
         log.setEnabled(false);
         log10.setEnabled(false);
          bkebnar.setEnabled(false);
    }//GEN-LAST:event_offActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mycal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mycal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mycal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mycal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mycal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acos;
    private javax.swing.JButton asin;
    private javax.swing.JButton atan;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bback;
    private javax.swing.JButton bceil;
    private javax.swing.JButton bclear;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bdot;
    private javax.swing.JButton bequal;
    private javax.swing.JButton bfloor;
    private javax.swing.JButton bkebnar;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bplus;
    private javax.swing.JButton bpower;
    private javax.swing.JButton bround;
    private javax.swing.JButton bsqrt;
    private javax.swing.JButton bsub;
    private javax.swing.JButton cos;
    private javax.swing.JButton cosh;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton log;
    private javax.swing.JButton log10;
    private javax.swing.JButton max;
    private javax.swing.JButton min;
    private javax.swing.JButton off;
    private javax.swing.JButton on;
    private javax.swing.JButton sin;
    private javax.swing.JButton sinh;
    private javax.swing.JTextField t1;
    private javax.swing.JButton tan;
    private javax.swing.JButton tanh;
    private javax.swing.JButton todegree;
    private javax.swing.JButton toradian;
    // End of variables declaration//GEN-END:variables
}
